In [1]:
import numpy as np

In [2]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]

sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

In [3]:
print("Sales Data:\n", sales_data)

Sales Data:
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]
 [     5 160000 185000 205000 230000]]


In [4]:
print(sales_data.shape)  # Output: (5, 5)

(5, 5)


In [5]:
print(sales_data[0:3,0:])

[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [9]:
print(np.sum(sales_data[:,1:],axis=0))
print(np.sum(sales_data[:,1:],axis=1))


[ 810000  945000 1085000 1240000]
[800000 610000 990000 900000 780000]


In [11]:
#minimum sales for each restaurant
min_sales = np.min(sales_data[:,1:], axis=1)
print("Minimum sales for each restaurant:", min_sales)

#maximum sales for each restaurant
max_sales = np.max(sales_data[:,1:], axis=1)
print("Maximum sales for each restaurant:", max_sales)

Minimum sales for each restaurant: [150000 120000 200000 180000 160000]
Maximum sales for each restaurant: [250000 190000 300000 270000 230000]


In [12]:
maximum_sales = np.max(sales_data[:,1:], axis=0)
print("Maximum sales for each year:", maximum_sales)

Maximum sales for each year: [200000 230000 260000 300000]


In [13]:
avg_sales = np.mean(sales_data[:,1:], axis=0)
print("Average sales for each year:", avg_sales)

Average sales for each year: [162000. 189000. 217000. 248000.]


In [14]:
avg_sales = np.mean(sales_data[:,1:], axis=1)
print("Average sales for each year:", avg_sales)

Average sales for each year: [200000. 152500. 247500. 225000. 195000.]


In [ ]:
cumsum = np.cumsum(sales_data[:,1:], axis=1)
print("Cumulative sales for each restaurant:\n", cumsum)

Cumulative sales for each year:
 [[150000 330000 550000 800000]
 [120000 260000 420000 610000]
 [200000 430000 690000 990000]
 [180000 390000 630000 900000]
 [160000 345000 550000 780000]]
