# Challenge Questions - NumPy

# Instructions:
• Please ensure you don't overwrite any existing cells. Add new cells below by pressing ALT+ENTER

• Attempt all of the questions

• You are encouraged to look online for help should you need it

# 

## Q1: Import the NumPy library

In [ ]:
#Type your code here


In [2]:
import numpy as np

## Q2: Create a 5 row by 3 column array that contains only the value 7

In [3]:
# Type your code here
arr = np.full((5,3),7)

In [4]:
arr

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

## Q3: Create a 3 row by 4 column array that contains evenly spaced values between 0-100

## Q4 Take the shape from Q3 and transform it so that the numbers increment down the columns rather than along the rows

In [ ]:
# Type your code here


## Q5 From the 2D array stored in the variable "a" below use slicing to return the below segment

In [7]:
# Run this cell first
a = np.linspace(0,24,num=25).reshape(5,5)
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [9]:
# Type your code here
a[2:4,1:4]

array([[11., 12., 13.],
       [16., 17., 18.]])

## Q6: Return only elements that are greater than 12 from the same array "a" as Q5

In [12]:
# Type your code herearr
a[a>12]

array([13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

## Q7: There is a file called 'tfl-daily-cycle-hires-2018.csv' saved in the same directory as this notebook. We will be needing only the "Number of Bicycle Hires" data.
1. Load and store it in a variable called tfl_18 and check the shape of the array. 
2. Check the shape of the array
3. Change the array to be a 2D array of shape (365,1)

### This file contains the daily cycle hire numbers for the year 2018.

### Hint: Consider the use of appropriate optional arguments in whatever function you choose to use.

In [7]:
# Load the data here
data = np.loadtxt("tfl-daily-cycle-hires-2018.csv", delimiter=",")
print(data)

ValueError: could not convert string '\ufeffDay' to float64 at row 0, column 1.

In [6]:
# Check the shape here
np.shape(data)

()

In [ ]:
# Change the shape here


## Q8: There is a file called 'tfl-daily-cycle-hires-2019.csv' saved in the same directory as this notebook. We will be needing only the "Number of Bicycle Hires" data.
1. Load and store it in a variable called tfl_19 and check the shape of the array. 
2. Check the shape of the array
3. Change the array to be a 2D array of shape (365,1)

In [ ]:
# Load the data here


In [ ]:
# Check the shape here


In [ ]:
# Change the shape here


## Q9: Create a new array called tfl_1819 that contains the two arrays tfl_18 and tfl_19 concatenated together on the 1 axis. The shape of tfl_1819 should be (365, 2)

In [ ]:
# Concatenate the arrays here


In [ ]:
# Check the shape here


## Q10 Perform the following operations on the concatenated array tfl_1819:
1. Find the sum of the columns, this shoe the total bike hires for 2018 and 2019
2. Find the average number of bike hires for both columns, this will show the average bike hires for 2018 and 2019
3. Find the maximum number of bike hires in both columns,  this will show the maximum bike figure for a single day in 2018 and 2019

In [ ]:
# Sum the columns here


In [ ]:
# Find the average of the columns here


In [ ]:
# Find the maximum of both columns here
