In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.4 MB 349.5 kB/s eta 0:00:35
   - -------------------------------------- 0.5/12.4 MB 349.5 kB/s eta 0:00:35
   - -------------------------------------- 0.5/12.4 MB 349.5 kB/s eta 0:00:35
   - -------------------------------------- 0.5/12.4 MB 349.5 kB/s eta 0:00:35
   - -------------------------------------- 0.5/12.4 MB 349.5 kB/s eta 0:00:35
   -- ------------------------------------- 0.8/12.4 MB 294.4 kB/s eta 0:00:40
   --- -----------------------------

In [3]:
import numpy as np

# 1d array 
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))
print(arr.ndim)  # number of dimensions
print(arr.shape)  # shape of the array

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
(5,)


In [6]:
# 2d array using numpy
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)
print(arr2d.ndim)  # number of dimensions
print(arr2d.shape)  # shape of the array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [10]:
np.arange(1,10,2).reshape(1,5)  # create an array with a range of values from 1 to 10 with a step of 2 and reshape it to a 2x2 array


array([[1, 3, 5, 7, 9]])

In [13]:
np.zeros((3, 4))  # Create a 3x4 array filled with zeros



array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((2, 3))  # Create a 2x3 array filled with ones


array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.eye(3)  # Create a 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# vectorized operation/ universal functions (ufuncs) in numpy are functions that operate element-wise on arrays. They are optimized for performance and can be used to perform mathematical operations on arrays without the need for explicit loops. Some common ufuncs include:

arr = np.array([1, 2, 3, 4, 5])

print(np.add(arr, 10))
print(np.subtract(arr, 2))
print(np.multiply(arr, 3))
print(np.divide(arr, 2))

[11 12 13 14 15]
[-1  0  1  2  3]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


In [19]:
# universal function

print(np.sqrt(arr))  # square root of each element in the array
print(np.exp(arr))  # exponential of each element in the array
print(np.log(arr))  # natural logarithm of each element in the array 

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [26]:
# indexing and slicing in numpy allows you to access and manipulate specific elements or subsets of an array. You can use integer indexing, boolean indexing, and slicing to extract data from arrays.

arr1= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr1[0, 1])  # Accessing the element at row 0, column 1
print(arr1[0:2, 0:2])


2
[[1 2]
 [4 5]]


In [ ]:
# modifying an element in the array
arr1[2][0]=2
print(arr1)  # Output: [[1 2 3] [4 5 6] [2 8 9]]

[[2 2 3]
 [4 5 6]
 [2 8 9]]


In [31]:
arr1[1:,1:]= 1
print(arr1)  # Output: [[1 2 3] [4 1 1] [2 1 1]]

[[2 2 3]
 [4 1 1]
 [2 1 1]]


In [32]:
# normalization of an array is the process of scaling the values in the array to a specific range, typically between 0 and 1. This can be useful for machine learning algorithms that are sensitive to the scale of input features.

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mean=np.mean(data, axis=0)  # calculate the mean of each column
std=np.std(data, axis=0)  # calculate the standard deviation of each column

#normalize the data by subtracting the mean and dividing by the standard deviation
normalized_data = (data - mean) / std
print(normalized_data)  # Output: [[-1.22474487 -1.22474487 -1.22474487] [ 0.          0.          0.        ] [ 1.22474487  1.22474487  1.22474487]]

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


In [38]:
m1 = np.array([[1,2,3,4],[5,6,7,8]])
m2 = np.array([[1,2,3,4],[5,6,7,8]])

print(np.add(m1[1: , 0:],m2[0:1 , 0:]))  # element-wise addition

[[ 6  8 10 12]]
